
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BaseButton': typeof import("../components/BaseButton.vue")['default']
    'EditAccountModal': typeof import("../components/EditAccountModal.vue")['default']
    'EditCustomerModal': typeof import("../components/EditCustomerModal.vue")['default']
    'EditEstimateModal': typeof import("../components/EditEstimateModal.vue")['default']
    'EditInvoiceModal': typeof import("../components/EditInvoiceModal.vue")['default']
    'EditProdServModal': typeof import("../components/EditProdServModal.vue")['default']
    'NewAccountModal': typeof import("../components/NewAccountModal.vue")['default']
    'NewCustomerModal': typeof import("../components/NewCustomerModal.vue")['default']
    'NewEstimateModal': typeof import("../components/NewEstimateModal.vue")['default']
    'NewInvoiceModal': typeof import("../components/NewInvoiceModal.vue")['default']
    'NewProdServModal': typeof import("../components/NewProdServModal.vue")['default']
    'NewTransactionModal': typeof import("../components/NewTransactionModal.vue")['default']
    'Sidebar': typeof import("../components/Sidebar.vue")['default']
    'StatusBadge': typeof import("../components/StatusBadge.vue")['default']
    'TablePageLayout': typeof import("../components/TablePageLayout.vue")['default']
    'TransactionDetailsModal': typeof import("../components/TransactionDetailsModal.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBaseButton': typeof import("../components/BaseButton.vue")['default']
    'LazyEditAccountModal': typeof import("../components/EditAccountModal.vue")['default']
    'LazyEditCustomerModal': typeof import("../components/EditCustomerModal.vue")['default']
    'LazyEditEstimateModal': typeof import("../components/EditEstimateModal.vue")['default']
    'LazyEditInvoiceModal': typeof import("../components/EditInvoiceModal.vue")['default']
    'LazyEditProdServModal': typeof import("../components/EditProdServModal.vue")['default']
    'LazyNewAccountModal': typeof import("../components/NewAccountModal.vue")['default']
    'LazyNewCustomerModal': typeof import("../components/NewCustomerModal.vue")['default']
    'LazyNewEstimateModal': typeof import("../components/NewEstimateModal.vue")['default']
    'LazyNewInvoiceModal': typeof import("../components/NewInvoiceModal.vue")['default']
    'LazyNewProdServModal': typeof import("../components/NewProdServModal.vue")['default']
    'LazyNewTransactionModal': typeof import("../components/NewTransactionModal.vue")['default']
    'LazySidebar': typeof import("../components/Sidebar.vue")['default']
    'LazyStatusBadge': typeof import("../components/StatusBadge.vue")['default']
    'LazyTablePageLayout': typeof import("../components/TablePageLayout.vue")['default']
    'LazyTransactionDetailsModal': typeof import("../components/TransactionDetailsModal.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BaseButton: typeof import("../components/BaseButton.vue")['default']
export const EditAccountModal: typeof import("../components/EditAccountModal.vue")['default']
export const EditCustomerModal: typeof import("../components/EditCustomerModal.vue")['default']
export const EditEstimateModal: typeof import("../components/EditEstimateModal.vue")['default']
export const EditInvoiceModal: typeof import("../components/EditInvoiceModal.vue")['default']
export const EditProdServModal: typeof import("../components/EditProdServModal.vue")['default']
export const NewAccountModal: typeof import("../components/NewAccountModal.vue")['default']
export const NewCustomerModal: typeof import("../components/NewCustomerModal.vue")['default']
export const NewEstimateModal: typeof import("../components/NewEstimateModal.vue")['default']
export const NewInvoiceModal: typeof import("../components/NewInvoiceModal.vue")['default']
export const NewProdServModal: typeof import("../components/NewProdServModal.vue")['default']
export const NewTransactionModal: typeof import("../components/NewTransactionModal.vue")['default']
export const Sidebar: typeof import("../components/Sidebar.vue")['default']
export const StatusBadge: typeof import("../components/StatusBadge.vue")['default']
export const TablePageLayout: typeof import("../components/TablePageLayout.vue")['default']
export const TransactionDetailsModal: typeof import("../components/TransactionDetailsModal.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBaseButton: typeof import("../components/BaseButton.vue")['default']
export const LazyEditAccountModal: typeof import("../components/EditAccountModal.vue")['default']
export const LazyEditCustomerModal: typeof import("../components/EditCustomerModal.vue")['default']
export const LazyEditEstimateModal: typeof import("../components/EditEstimateModal.vue")['default']
export const LazyEditInvoiceModal: typeof import("../components/EditInvoiceModal.vue")['default']
export const LazyEditProdServModal: typeof import("../components/EditProdServModal.vue")['default']
export const LazyNewAccountModal: typeof import("../components/NewAccountModal.vue")['default']
export const LazyNewCustomerModal: typeof import("../components/NewCustomerModal.vue")['default']
export const LazyNewEstimateModal: typeof import("../components/NewEstimateModal.vue")['default']
export const LazyNewInvoiceModal: typeof import("../components/NewInvoiceModal.vue")['default']
export const LazyNewProdServModal: typeof import("../components/NewProdServModal.vue")['default']
export const LazyNewTransactionModal: typeof import("../components/NewTransactionModal.vue")['default']
export const LazySidebar: typeof import("../components/Sidebar.vue")['default']
export const LazyStatusBadge: typeof import("../components/StatusBadge.vue")['default']
export const LazyTablePageLayout: typeof import("../components/TablePageLayout.vue")['default']
export const LazyTransactionDetailsModal: typeof import("../components/TransactionDetailsModal.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
