// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/11/2025, 9:07:51 PM
const configMerger = require("C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/composables/**/*.{js,ts,mjs}","C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/utils/**/*.{js,ts,mjs}","C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/aryan/OneDrive/Desktop/Accounting_Software/frontend/app.config.{js,ts,mjs}"] } }));

module.exports = config
