openapi: 3.0.0
info:
  title: Company Settings API
  description: API for managing company settings, including company name, type, contact info, and address.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
    description: Local development server
paths:
   /api/company/create_company:
    post:
      summary: Create a company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        201:
          description: Company created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Company created successfully.
                  company:
                    $ref: '#/components/schemas/Company'
        400:
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        409:
          description: Company already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
   /api/company/get_company:
    get:
      summary: Retrieve company details
      responses:
        200:
          description: Successfully retrieved company details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        404:
          description: Company not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
   /api/company/update_company:
    patch:
        summary: Update company details
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        responses:
          200:
            description: Company updated successfully.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Company updated successfully.
                    company:
                      $ref: '#/components/schemas/Company'
          400:
            description: Invalid input.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
          404:
            description: Company not found.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

   /api/company/delete_company:
    delete:
      summary: Delete a company
      responses:
        200:
          description: Company deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Company deleted successfully.
        404:
          description: Company not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    Company:
      type: object
      properties:
      
        company_name_info:
          type: object
          properties:
  
            company_name:
              type: string
              description: Name of the company.
              
            legal_name:
              type: string
              description: Legal name of the company.
            same_as_company_name:
              type: boolean
              description: Whether the legal name is the same as the company name
              
            identity:
              type: string
              description: SSN or EIN of the company.
              enum:
                - SSN
                - EIN
            tax_id:
              type: string
              description: Tax ID of the company.
          
        company_type:
          type: object
          properties:
  
            tax_form:
              type: string
              description: Tax form used by the company.
              enum:
                - Sole Proprietor (Form 1040)
                - Partnership or limited liability company (Form 1065)
                - Small Business corporation, two or more owners (Form 1120S)
                - Corporation, one or more shareholders (Form 1120)
                - Nonprofit organization (Form 990)
                - Limited Liability
                - Other (Please specify)
                
            industry:
              type: string
              description: Industry of the company.
  
        contact_info:
          type: object
          properties:
  
            company_email:
              type: string
              description: Email for company correspondence.
              
            customer_facing_email:
              type: string
              description: Email shown to customers.
              
            same_as_company_email:
              type: boolean
              description: Indicates if the customer-facing email is the same as the company email.
              
            company_phone:
              type: string
              description: Contact phone number.
              
            website:
              type: string
              description: Website URL of the company.
  
        Address:
          type: object
          properties:
  
            company_address:
              type: object
              properties:
              
                street:
                  type: string
                  description: Street address of the company.
                  
                city:
                  type: string
                  description: City where the company is located.
                  
                state:
                  type: string
                  description: State where the company is located.
                  enum:
                    - Alabama
                    - Alaska
                    - Arizona
                    - Arkansas
                    - California
                    - Colorado
                    - Connecticut
                    - Delaware
                    - Florida
                    - Georgia
                    - Hawaii
                    - Idaho
                    - Illinois
                    - Indiana
                    - Iowa
                    - Kansas
                    - Kentucky
                    - Louisiana
                    - Maine
                    - Maryland
                    - Massachusetts
                    - Michigan
                    - Minnesota
                    - Mississippi
                    - Missouri
                    - Montana
                    - Nebraska
                    - Nevada
                    - New Hampshire
                    - New Jersey
                    - New Mexico
                    - New York
                    - North Carolina
                    - North Dakota
                    - Ohio
                    - Oklahoma
                    - Oregon
                    - Pennsylvania
                    - Rhode Island
                    - South Carolina
                    - South Dakota
                    - Tennessee
                    - Texas
                    - Utah
                    - Vermont
                    - Virginia
                    - Washington
                    - West Virginia
                    - Wisconsin
                    - Wyoming
                    
                zipcode:
                  type: integer
                  description: ZIP code of the company location.
                  
              required:
                  - street
                  - city
                  - state
                  - zipcode
  
            legal_address:
              type: object
              properties:
              
                street:
                  type: string
                  description: Street address of the company.
                  
                city:
                  type: string
                  description: City where the company is located.
                  
                state:
                  type: string
                  description: State where the company is located.
                  enum:
                    - Alabama
                    - Alaska
                    - Arizona
                    - Arkansas
                    - California
                    - Colorado
                    - Connecticut
                    - Delaware
                    - Florida
                    - Georgia
                    - Hawaii
                    - Idaho
                    - Illinois
                    - Indiana
                    - Iowa
                    - Kansas
                    - Kentucky
                    - Louisiana
                    - Maine
                    - Maryland
                    - Massachusetts
                    - Michigan
                    - Minnesota
                    - Mississippi
                    - Missouri
                    - Montana
                    - Nebraska
                    - Nevada
                    - New Hampshire
                    - New Jersey
                    - New Mexico
                    - New York
                    - North Carolina
                    - North Dakota
                    - Ohio
                    - Oklahoma
                    - Oregon
                    - Pennsylvania
                    - Rhode Island
                    - South Carolina
                    - South Dakota
                    - Tennessee
                    - Texas
                    - Utah
                    - Vermont
                    - Virginia
                    - Washington
                    - West Virginia
                    - Wisconsin
                    - Wyoming
                    
                zipcode:
                  type: integer
                  description: ZIP code of the company location.
                  
              required:
                  - street
                  - city
                  - state
                  - zipcode  
            same_as_company_address:
              type: boolean
              description: Indicates if the selected address is the same as the company address.
                   
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message describing the issue.
